<a href="https://colab.research.google.com/github/mingma1369/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
print('hello world')
import numpy as np

list_1=[1,2,3,4]
array_1=np.array(list_1)
array_1

list_2=[11,22,33,44]
lists=[list_1,list_2]

array_2=np.array(lists)

array_2
array_2.dtype
array_2.shape

my_zeros_array=np.zeros(5)
my_zeros_array.dtype

my_empty_array=np.empty(5)
my_empty_array
my_empty_array.dtype

my_empty_array==my_zeros_array

my_ones_array=np.ones([5,5])
my_ones_array


my_eye_array=np.eye(5)
my_eye_array 

np.arange(5)
np.arange(1,5)
np.arange(1,5,2)

# 
arr1=np.array([[1,2,3,4],[8,9,10,11]])

arr1+arr1
arr1-arr1
arr1*arr1
1/arr1
arr1**3
# 

arr=np.arange(0,11)
arr

arr[8]
arr[0:3]
arr[1:5]
arr[0:5]

arr[0:5]=100
arr

arr=np.arange(0,11)
arr
slice_of_arr=arr[0:5]
slice_of_arr

slice_of_arr[:]=99
slice_of_arr
arr 

arr_copy=arr.copy()


arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d
arr_2d[1]
arr_2d[0]
arr_2d[1][0]
arr_2d[:2][1:]

arr2d=np.zeros((10,10))
arr2d
arr2d_length=arr2d.shape()

In [ ]:
list_1=[1,2,3,4]
list_2=[5,6,7,8]

In [ ]:
array1=np.array(list_1)
array1

array([1, 2, 3, 4])

In [ ]:
array2=np.array([list_1,list_2])
array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
df=pd.read_csv('/content/sample_data/california_housing_test.csv')

In [ ]:
df.head(10)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   
5    -119.56     36.51                37.0       1018.0           213.0   
6    -121.43     38.63                43.0       1009.0           225.0   
7    -120.65     35.48                19.0       2310.0           471.0   
8    -122.84     38.40                15.0       3080.0           617.0   
9    -118.02     34.08                31.0       2402.0           632.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0  
5       663.0       204.0         1.6635             67000.0  
6       604.0       218.0         1.6641             67000.0  
7      1341.0       441.0         3.2250            166900.0  
8      1446.0       599.0         3.6696            194400.0  
9      2830.0       603.0         2.3333            164200.0

In [ ]:
df['total_rooms']

0       3885.0
1       1510.0
2       3589.0
3         67.0
4       1241.0
         ...  
2995    1450.0
2996    5257.0
2997     956.0
2998      96.0
2999    1765.0
Name: total_rooms, Length: 3000, dtype: float64

In [ ]:
df.rename['total_rooms','rooms']

TypeError: ignored

In [ ]:
arr2d=np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
arr_length=arr2d.shape[1]
arr_length

10

In [ ]:
for i in range (arr_length):
  arr2d[i]=1


In [ ]:
arr2d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
for i in range(arr_length):
  arr2d[i]=i

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [ ]:
arr=np.arange(50).reshape(10,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [ ]:
 arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [ ]:
np.dot(arr.T,arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [ ]:
arr3d=np.arange(50).reshape((5,5,2))
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [ ]:
arr3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

In [ ]:
arr=np.array([[1,2,3]])
arr

array([[1, 2, 3]])

In [ ]:
arr.swapaxes(0,1)

array([[1],
       [2],
       [3]])

Array unicersal array functions

In [ ]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [ ]:
A=np.random.randn(10)
A

array([-0.35481237, -0.22946337, -0.77774718,  1.98386956,  1.1558947 ,
       -0.5485836 , -0.38655485,  0.65760491, -1.0590033 , -1.03907003])

In [ ]:
B=np.random.randn(10)
B

array([ 1.40787636, -0.19690316, -0.43714386,  0.82971878, -0.95158548,
        0.2950842 ,  0.64947366,  0.19116575,  0.62573084,  0.65359646])

In [ ]:
#Binary Fucntions
np.add(A,B)

array([ 1.05306399, -0.42636653, -1.21489105,  2.81358834,  0.20430922,
       -0.2534994 ,  0.26291881,  0.84877066, -0.43327247, -0.38547356])

In [ ]:
np.maximum(A,B)

array([ 1.40787636, -0.19690316, -0.43714386,  1.98386956,  1.1558947 ,
        0.2950842 ,  0.64947366,  0.65760491,  0.62573084,  0.65359646])